GoodPlaces/Web/ViewModels/Places/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GoodPlaces.Model;
using GoodPlaces.ViewModels.Core;
using GoodPlaces.App.Services;
using NHibernate;
using NHibernate.Linq;

namespace GoodPlaces.ViewModels.Places
{
    public class DetailsViewModel : BaseViewModel
    {
        private readonly User _user;
		private readonly ISession _session;
        private readonly RestaurantService _resService;
		//public Implicit Implicit { get; private set; }
		//public Recommendations Recommendations { get; private set; }
        public Restaurant restaurant { get; private set; }
        public int favoriteCount { get; private set; }
        public int beenThereCount { get; private set; }
        public float battingAverage { get; private set; }

        public DetailsViewModel(Restaurant res, User user, ISession session): base()
		{
			_user = user;
			_session = session;
            _resService = new RestaurantService(session);
            restaurant = res;
            favoriteCount = _resService.GetFavoriteCount(res.Id);
            battingAverage = _resService.GetBattingAverage(res.Id);
            beenThereCount = _resService.GetUsersCount(res.Id);
			//Implicit = new Implicit(_user, _session);
			//Recommendations = new Recommendations(_user, _session);
		}

    }
}

GoodPlaces/Web/Controllers/InController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using GoodPlaces.App.Services;
using GoodPlaces.App.Services.FacebookModel;
using GoodPlaces.Utilities;
using NHibernate;
using NHibernate.Linq;
using User = GoodPlaces.Model.User;

namespace GoodPlaces.Controllers
{
	public class InController : Controller
	{
		private readonly FacebookService _facebookService;
		private readonly ISession _session;

		public InController(ISession session, FacebookService facebookService)
		{
			_session = session;
			_facebookService = facebookService;
		}

		public ActionResult Index()
		{
			return RedirectToAction("Index", "Home");
		}

		public ActionResult Bye()
		{
			FormsAuthentication.SignOut();

			return Redirect("/");
		}

		[HttpPost]
		public ActionResult Index(string connect, string returnUrl)
		{
#if OFFLINEDEBUG
			var user = _session.Query<User>().FirstOrDefault();
			if (user != null)
				return Authenticate(user, returnUrl);
#endif

			return RedirectToAction("Connect", new {returnUrl});
		}

		public ActionResult Connect(string code, string returnUrl)
		{
			var currentUrl = Request.Url.AbsoluteUri;
			var fbUrl = _facebookService.GetRedirectUrl(currentUrl);
	
			if (String.IsNullOrWhiteSpace(code))
				return Redirect(fbUrl);

			string token = _facebookService.GetAccessToken(code, currentUrl);

			if (String.IsNullOrEmpty(token))
				return RedirectToAction("Index", "Home", new {reason = "token_is_null"});

			var u = _facebookService.GetMe(token);
			if (u == null)
				return RedirectToAction("Index", "Home", new { reason = "user_is_null" });

			long uid = long.Parse(u.id);

			var user = _session.Query<User>().FirstOrDefault(x => x.FacebookId == uid);
			if (user == null)
			{
				user = new User
					       {
						       FacebookAccessToken = token,
						       FacebookId = uid,
						       FirstName = u.first_name,
						       LastName = u.last_name,
							   Email = u.email
					       };
                user.ImageUrl = FacebookService.GetProfileImage(token);
				_session.Save(user);
				_session.Flush();
			}

			return Authenticate(user, returnUrl);
		}

		private ActionResult Authenticate(User user, string returnUrl)
		{
			FormsAuthentication.SetAuthCookie(user.Id.ToString(), true);

			if (String.IsNullOrWhiteSpace(returnUrl))
				return RedirectToAction("Index", "Places");

			return Redirect(returnUrl);
		}
	}
}

GoodPlaces/Web/Views/Shared/Create.cshtml
@using BootstrapSupport
@model Object
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset class="form-horizontal">
        <legend>@Model.GetLabel() <small>Details</small></legend>
        @foreach (var property in Model.VisibleProperties())
        {
            @Html.BeginControlGroupFor(property.Name)
                @Html.Label(property.Name.ToSeparatedWords(), new { @class = "control-label" })
                <div class="controls">
                    @Html.Editor(property.Name, new { @class = "input-xlarge" })
                    @Html.ValidationMessage(property.Name, null, new { @class = "help-inline" })
		        </div>
            @Html.EndControlGroup()
        }
		<div class="form-actions">
            <button type="submit" class="btn btn-primary">Save changes</button>
            <button class="btn">Cancel</button>
          </div>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GoodPlaces/Web/Views/Shared/Details.cshtml
@using BootstrapSupport
@model Object
<fieldset>
    <legend>@Model.GetLabel() <small>Details</small></legend>
    <dl> <!-- use this class on the dl if you want horizontal styling http://twitter.github.com/bootstrap/base-css.html#typography  class="dl-horizontal"-->     
        @foreach(var property in Model.VisibleProperties())
        {
            <dt>
                @property.GetLabel().ToSeparatedWords()
            </dt>
            <dd>
                @Html.Display(property.Name)                
            </dd>
        }
    </dl>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", Model.GetIdValue()) |
    @Html.ActionLink("Back to List", "Index")
</p>

GoodPlaces/Web/Views/Shared/Tracking.cshtml
@if (!Request.IsLocal) {
	<script type="text/javascript">

		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-675566-24']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script');
			ga.type = 'text/javascript';
			ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(ga, s);
		})();

	</script>
}

GoodPlaces/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>@ViewBag.Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        @Styles.Render(ViewBag.Style)
        @RenderSection("head", required: false)
		@Html.Partial("Tracking")
    </head>
	<body>
            <div id="topbar">
                <div id="topbar-content">
                    @if(!ViewBag.NoLogo) {
                        <a href="/" class="logo">&nbsp;</a>
                    }
                    @if(ViewBag.CurrentUser != null) {
                        <span class="welcome">Welcome, <a href="/profile">@ViewBag.CurrentUser.FirstName!</a></span>
                        <a href="@Url.Action("Bye", "In")" class="signout">Sign out</a>
                    }
                </div>
            </div>

		<div id="content">
			@Html.Partial("_alerts")
			@RenderBody()
		</div>
		
		@Scripts.Render("~/js")
		@RenderSection("Scripts", required: false)
	</body>
</html>

GoodPlaces/Web/Views/Shared/_alerts.cshtml
@using BootstrapSupport
@if (TempData.ContainsKey(Alerts.ATTENTION))
{
    <div class="alert alert-block">
        <a class="close" data-dismiss="alert" href="#">x</a>
        <h4 class="alert-heading">Attenion!</h4>
        @TempData[Alerts.ATTENTION]
    </div>
}
@foreach(string key in Alerts.ALL)
    {
        if (TempData.ContainsKey(key))
         {
             <div class="alert alert-@key">
                 @TempData[key]
             </div>
         }
    }
                

GoodPlaces/Web/Views/Shared/_html5shiv.cshtml
   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="~/scripts/html5.js"></script>
    <![endif]-->